#renames born-digital tiff files generated by Automator (when converting from PDF) to comply with Veridian naming conventions
#assumes the correct filename prefix
#assumes the .tiff suffix
#dependency: rename http://plasmasturm.org/code/rename/

rename -s _01.tiff '_01 01.tiff' *
rename -s _02.tiff '_02 01.tiff' *
rename -s ' 2.tiff' ' 02.tiff' *
rename -s ' 3.tiff' ' 03.tiff' *
rename -s ' 4.tiff' ' 04.tiff' *
rename -s ' 5.tiff' ' 05.tiff' *
rename -s ' 6.tiff' ' 06.tiff' *
rename -s ' 7.tiff' ' 07.tiff' *
rename -s ' 8.tiff' ' 08.tiff' *
rename -s ' 9.tiff' ' 09.tiff' *
rename -s ' ' '_00' *
rename -s .tiff .tif *

